spring:
  data:
    redis:
      host: localhost # redis host 입력
      port: 6379 # redis port 입력

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver # DB driver
    url: jdbc:mysql://localhost:3306/querydsl?serverTimezone=UTC # DB url
    username: root # DB ?? username
    password: root # DB ?? password

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect # ???? ??? DB dialect
        show_sql: true # console? ???? sql ??
        format_sql: true # sql ?? ? ?? ?? format ??