stages:
  - build
  - package
  - deploy

variables:
  IMAGE_NAME: $CI_REGISTRY_IMAGE/next-img
  CONTAINER_NAME: next-con

build:
  image: node:16.14.0
  stage: build
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - .next
      - node_modules
    expire_in: 1 days

package:
  image: docker:latest
  stage: package
  services:
    - docker:dind
  before_script:
    - docker login $CI_REGISTRY -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
  script:
    - docker build -t $IMAGE_NAME .
    - docker push $IMAGE_NAME
  after_script:
    - docker logout

deploy:
  stage: deploy
  tags:
    - client
  before_script:
    - docker login $CI_REGISTRY -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
  script:
    - docker rm -f $CONTAINER_NAME || true
    - docker rmi $IMAGE_NAME || true
    - docker pull $IMAGE_NAME
    - docker run --name $CONTAINER_NAME -p 8088:8088 --restart always -d $IMAGE_NAME
  after_script:
    - docker logout